import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'All Recipes',
  ),
  Category(
    id: 'c2',
    title: 'My Recipes',
  ),
  Category(
    id: 'c3',
    title: 'Appetizers & Dips',
  ),
  Category(
    id: 'c4',
    title: 'Breakfast',
  ),
  Category(
    id: 'c5',
    title: 'Salads',
  ),
  Category(id: 'c6', title: 'Dinner'),
  Category(id: 'c7', title: 'Veggies'),
  Category(
    id: 'c8',
    title: 'Seafood',
  ),
  Category(
    id: 'c9',
    title: 'Bread',
  ),
  Category(
    id: 'c10',
    title: 'Soups',
  ),
  Category(
    id: 'c11',
    title: 'Sauces & Glazes',
  ),
  Category(
    id: 'c12',
    title: 'Desert',
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c5',
    ],
    title: 'Macaroni Salad',
    author: 'Linda Lovato',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.simplyhappyfoodie.com/wp-content/uploads/2019/06/classic-macaroni-salad-1.jpg',
    duration: 20,
    descriptions: [
      'One of Linda\'s favorites from her mother, she remembers this being one of her families favorites since they were little. Her mom always had to make a double batch. They don\'t have ingredient amounts maybe that\'s why I think of her making a double batch!',
    ],
    ingredients: [
      'Elbow Macaroni',
      'CHopped Celery',
      'Minced Red Onion',
      '3 cans of Tuna',
      'Cubbed Velveta',
      'Chopped Pimento Cheese',
      'Chopped Green Olives-(save some of the juice)',
      'Mayonaise and Mustard (Preferably Dijon but regular works)',
      'Salt and Pepper'
    ],
    steps: [
      'Her mother gave her the recipe this weay with the description of \"A pinch of this, and a pinch of that, just be sure to boil the macaroni!\"',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c1',
      'c5',
    ],
    title: 'Greek Salad',
    author: 'Nana',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.simplyrecipes.com/thmb/mYL1tCuInryTdY6hRsZXuXWr2-Q=/1600x1067/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2011__08__dads-greek-salad-horiz-a-1600-bc71b85bc907414a9bb3179a923b58fc.jpg',
    duration: 10,
    descriptions: [
      'First had/made this salad in Cheyenne, WY for a pot luck at a church function.  This recipe was adopted from “Anne Willan’s LOOK & COOK – Superb Salads” 1993'
    ],
    ingredients: [
      '2 lbs - Medium tomatoes (use the ripest tomatoes available)',
      '2 - Medium Cucumbers',
      '2 - Green Bell Peppers',
      '1 - Medium Red Onion',
      '6oz - Feta Cheese'
          '1/4 cup - Kalamata or other Greek Olives.',
      '',
      'Vinaigrette Dressing'
          '3-5 - Sprigs of Fresh Mint',
      '3-5 - Sprigs of Fresh Oregano',
      '7-10 - Sprigs of Parsley',
      '3 tbsp - Red Wine Vinegar',
      '1/2 c - Extra Virgin Olive Oil',
      'Salat and Pepper to taste'
    ],
    steps: [
      'Start with Vinaigrette.  Strip the mint, oregano, and parsley leaves from the stems and coarsely chop.  In a bowl whisk together the red wine vinegar, salt, and pepper.  Gradually whisk in the oil so the vinaigrette dressing emulsifies and thickens slightly—then add chopped herbs.  This vinaigrette can be kept for several days.',
      'Prepare the vegetables',
      'Cut tomatoes, cucumber, bell peppers, and feta into bite sizes pieces.  Slice the onion in thin slices.  Mix all together then add vinaigrette.  Adjust seasoning to taste.  Add olives and feta cheese and gently toss.  Let sit for 30-minutes before serving.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c1',
      'c11',
    ],
    title: 'Tequila-Lime BBQ Sauce',
    author: 'Tata',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F8088309.jpg',
    duration: 45,
    descriptions: [
      'Tata was getting pretty good with the smoker a friend gave him, excelling at BBQ Ribs and Pulled Pork (pork butt).  However, he felt that to become a true BBQ’er he needed to come up with his own BBQ Sauce recipe -- He\'s been making BBQ Sauces for years, ever since his brother-in-law (Ronnie Jones) taught him how to “doctor” up bottled BBQ sauce.  Unfortunatelyt none were really his “signature sauce.” With this recipe he was trying to capture a Mexican theme. Viva La Raza, what’s more Mexican than Tequila, Lime, and panocha {piloncillo}.  In the markets of Mexicali (down in El Hoyo) in large baskets you can find just about all the ingredients (except maybe Worcestershire and the A-1) for this BBQ Sauce.  By the way, when making this receipe, the water should be taken from faucet facing towards Mexico or at least taken from the faucet in the Southern most-part of the house to make it more Mexican. This recipe makes about 1 ½ pints.'
    ],
    ingredients: [
      '1 - Piloncillo cone …aka ..Panocha …  Mexican cane sugar  (about 125 gr) {See Note below}raw” sugar like demerara or turbinado sugar',
      '1 ½C - Ketchup',
      '6 oz - Water',
      '4 oz - Distilled White Vinegar',
      '2 - Large bay leaves (dried or fresh)',
      '2 - Cloves garlic, smashed',
      '¼ tsp - Cayenne power',
      '½ tsp - Mustard power',
      '½ - Small onion ',
      '1 tsp - Worcestershire Sauce',
      '1 tbls - A-1 Steak Sauce',
      '1 pinch - Salt',
      '1 - Lime, Juiced',
      '1 tbls - Good Gold Tequila (Optional)',
    ],
    steps: [
      'Place all ingredients except Tequila and lime juice in a pot at medium high heat.',
      'No need to break down the pilocillo, the liquid and heat will melt it down). ',
      'The half onion should be in one piece, just drop it in the pot.',
      'Stir frequently until it reaches a slow boil.',
      'When it comes to a boil, reduce heat to low, add the juice of 1 lime and simmer for about an hour or until sauce reduces down. Stir occasionally.',
      'Remove from heat and add Tequila; set aside and allow sauce to cool a bit.  Note: remove onion and bay leaves; the garlic can also be removed or just leave it in the sauce.',
      'NOTE: Instead of Piloncillo you can use a “raw” sugar like demerara or turbinado sugar or even dark brown sugar with a little molasses. Not difficult to make, just gather ingredient, boil, then simmer.   I was shooting for a somewhat thin vinegary sauce with a spicy kick. If too thin—reduce water; if too vinegary—reduce vinegar; if too spicy—reduce cayenne.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c1',
      'c6',
      'c8',
    ],
    title: 'Andy\'s Gumbo',
    author: 'Andy',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://hips.hearstapps.com/del.h-cdn.co/assets/17/31/1501791933-delish-gumbo-horizontal.jpg',
    duration: 60,
    descriptions: [
      '"Verse from Tata": One weekend in the summer 1989, my son—Andy—and I were home alone and we decide to cook something together.  Parts of this recipe came from a TV program that was on TV at the time, part was from a book called “The Little Gumbo Book”, and the other part Andy and I made up.'
    ],
    ingredients: [
      'ROUX',
      '4 tbsp - Flour',
      '4 tbsp - Bacon fat or oil',
      'Holy Trinity',
      '1 cup - Onion, chopped',
      '1 cup - Celery, Chopped',
      '1 cup - Bell Peppers, Chopped',
      'Veggies',
      '1 pkg - Okra, cut',
      '1 can - Whole tomatoes 16oz',
      'Liquid'
          '3 cups  Broth or stock (amount estimated)',
      'Chicken',
      'Sausage',
      'Shrimp',
    ],
    steps: [
      'NOTE: This recipe is best made in a large pot or Dutch Oven with enough room for stirring.',
      'On high heat, add a small amount of oil in the large pot or Dutch Over then added Holy Trinity stirring until onions are soft.',
      'Lower heat to medium and add roux and okra and cook a few minutes or until okra loses its sliminess.',
      'Slightly chop the tomatoes and add, along with the Broth, sausage,  and chicken.  Bring to boil then reduce heat to high simmer.',
      'Simmer for about 20-30 minutes. Add shrimp and cook thoroughly.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c1',
      'c3',
      'c6',
      'c8',
    ],
    title: 'Garlic Shrip with White Wine and Saffron',
    author: 'Tata',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://sarahscucinabella.com/wp-content/uploads/2009/05/Shrimp-in-White-Wine-and-Garlic-Sauce.jpg',
    duration: 15,
    descriptions: [
      'Ecerp from Tata: My Compa Ronnie and Irene were coming over to spend the weekend.  I wanted to cook something different that they hadn’t tried before.  Something light but on the gourmet side. I decided on shrimp.  I served the garlic shrimp with cooked Orzo with butter and dill weed.'
    ],
    ingredients: [
      '1 ½ - Jumbo Shrimp (16/20), peeled and deveined',
      '4 - Large mushrooms; cut into “thick” slices',
      '1  Onion',
      '6 or 7 - Cloves Garlic or to taste',
      '1 cup - Chicken stock',
      '1 cup - White Wine',
      '2 - Bay leaves',
      '½ lbs - Sweet butter',
      '¼ cup - Heavy Cream',
      '2 tbl - Corn Starch',
      'Few Strands of Saffron',
      '2 tbl - Cappers (optional)',
      'Pinch - Sea Salt',
      'Pinch - White pepper',
    ],
    steps: [
      'In a large pan, lightly sauté onions, garlic, and mushrooms.',
      ' Turn heat to high and slowly add shrimp.',
      'Mix saffron with chicken stock and wine, add to shrimp along with bay leaves, cappers then bring to simmer.',
      'Season with salt and white pepper to taste.  Add butter and cream and simmer for a few minutes (do not boil or cream will break down). If required, thicken with surrey of water and corn starch.',
      ' Remove bay leaves before serving.  Serve with Orzo with butter and dill weed'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c1',
      'c6',
      'c8',
    ],
    title: 'Salt Encased Fish',
    author: 'TV',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://eatyourworld.com/images/content_images/images/salted-fish4.jpg',
    duration: 240,
    descriptions: [
      'This recipe, more or less, came from one of those cooking shows on TV…I think it was “Good Eats” .  It has been made this several times.  Its a great dish to make to “show-off" by bring dish to table and cracking the salt.'
    ],
    ingredients: [
      '1 - Whole 3 or 4 lbs striped bass or red snapper.  The fish should be cleaned (gutted)',
      '5-8 - Egg whites',
      '2 lbs - Kosher Salt',
      '1 - Bunch aromatics',
    ],
    steps: [
      'Add aromatics inside fish, e.g. rosemary, basil, lemon grass, thyme, fresh oregano, etc.  then set fish aside',
      'Add whisked egg whites to 2-pounds of salt until salt has consistency of wet sand. ',
      'Place a ½ inch layer of salt on baking sheet, enough to place fish on, use remaining salt to cover fish.  Set oven to 425°',
      'Place in oven for 25-30 minutes.',
      'The salt will harden,  to serve break salt to remove fish.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c1',
      'c7',
      'c10',
    ],
    title: 'Gazpacho Smoothie',
    author: 'Tata',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://369t7u43n93dgc5pt43uc681-wpengine.netdna-ssl.com/wp-content/uploads/2014/07/DSC_0228-1.jpg',
    duration: 20,
    descriptions: [
      'Makes about one 16-oz serving. Verse from Tata : "My sister Rosa was thinking about selling health smoothies.  She ask me for ideas—I came up with a “knock-off” of Spanish Gazpacho.  As a selling point, I added the benefits of the smoothie", This smoothie features tomatoes and cucumbers.  This smoothie is an excellent source of antioxidants and the cucumber\'s high water content (about 95%) helps re-hydrate the body.  Other health benefits: Tomatoes contain compounds that have been proven to help prevent cancer, heart disease, cataracts and many others; while the potassium and manganese found in the cucumber\'s rich skin help regulate blood pressure and help promote nutrient functions, respectively'
    ],
    ingredients: [
      '2 - Fresh Roma tomatoes about 190 grams',
      '¼ - Cucumber seeded but with peel about 80-90 grams',
      '1 - Small can tomato juice 5.5 oz',
      '1 - Small piece bell pepper about 30 grams',
      '½ - Celery stalk about 25 grams',
      '½ - Tsp Onion powder',
      '¼ - Tsp garlic, granular',
      '1 - Tsp olive oil',
      '¾ - Tbsp kosher salt',
      '¼ - Juice of ¼ small lemon',
      '2 - Fresh basil leafs {optional}',
      '3 - Dashes {or to taste} Tapatio, Tabasco, or other vinegar based chile sauce.',
      '2 or 3 - Ice cubes',
    ],
    steps: [
      'Roughly chop up veggies'
          'Place all ingredients into a blender and blend until smooth.',
      'Can garnish the top part of a celery stalk or a finger slide of cucumber.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c1',
      'c6',
      'c8',
    ],
    title: 'Lobster & Shrip Pasta',
    author: 'Tata',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://i.pinimg.com/originals/d4/7b/d2/d47bd293cd91f896578d6b17f0a7fd41.jpg',
    duration: 35,
    descriptions: [
      'Verse From Tata: "My Compa Bass loves Calamari, so I was planning a calamari dish with a small lobster tail for his birthday—I was planning on four people for dinner; BUT at the last minute I was told there would be about 10 for dinner and I only had four small lobster tails.  I live in Phx but was cooking in Holtville, CA—no place to buy more lobster (besides I couldn’t afford six more lobster.  Therefore, I decided to cook the lobster and stir-fry with veggies or something to “stretch” out the lobster.  This is what I came out with.  This is more or less what I did because I just threw stuff together."',
      'Done in several step.',
      'Cook the lobster',
      'Cook the pasta',
      'Make the sauce',
      'Combine all',
    ],
    ingredients: [
      '4 - small lobster tails (4oz ea or two 8-oz tails)',
      '8-oz - Cooked shrimp',
      '3 tbsp - Flour',
      '3-oz - Butter',
      '3 clove of Garlic (minced) ',
      '1/4 - Small Onion',
      '2 - Bay Leaves',
      '2 leaves of Fresh basil',
      '1 bushell of Dill Weed',
      '8 oz - Pasta—small penne',
      '1 cup of Heavy cream or half-and-half',
      'Shredded parmesan (top to preference)',
      'White wine (optional)',
      'Olive oil',
      '1/4 cup - Capers',
    ],
    steps: [
      '**Lobster**',
      ' In small pot of water (just enough to cover tails) add bay leaf, onion, salt, and garlic then bring to rapid boil.',
      'Add lobster tail and turn heat down to slow boil—medium heat.',
      'Cook until lobster is just done—the shells will turn red in color—do not overcook. About 10 minutes -- Do not exceed 1 minute per oz.',
      'They’ll continue to cook slightly when added to the sauce.'
          'Remove lobsters from liquid, retain about 1 ½ cups of liquid for use in the sauce.',
      'Remove the meat from the shell, cut into bite size pieces and set aside—retain the lobster tail shells',
      '',
      '**Sauce**',
      'Place 2 or 3 ounces of butter, a clove of garlic and the lobster shells in pan over medium heat stirring/cooking for a couple of minutes.',
      'Remove the garlic and shells then add 3 Tbs flour into pan, stirring constantly until mixture/roux turn a “light”  color (like coffee w/cream).',
      ' Reduce heat to medium-low and slowly added about a cup of the retained liquid from the when you boiled the lobsters stirring quickly as you add liquid.',
      'Add the heavy cream, basil, butter, capers and wine if using.  (Make sure heat is not to high; otherwise cream will curdle)',
      'Add the lobster bites and shrimp then simmer for a few minutes.',
      'Remove from heat – keep warm.',
      '**Pasta**',
      'Cook the pasta “al-dente” using package instructions',
      'While pasta is cooking finely chop the about a third of the basil (stack leaves, roll up, and slice/cut the rolledup leaves)',
      'When done remove from water, add olive oil, chopped basil, dill weed, and shredded parmesan – mix/toss well',
      '',
      'Move pasta to serving platter, add sauce, and garnish with parmesan and basil'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c1',
      'c12',
    ],
    title: 'Chocolate Cake',
    author: 'Tata',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://images-gmi-pmc.edge-generalmills.com/5b77523f-273a-4da5-98f5-d45e8cb21508.jpg',
    duration: 45,
    descriptions: [
      'Verse From Tata "While working in Phoenix, I decided to make a birthday cake for one of my co-workers (Angel Lopez).  I was told his favorite cake was chocolate.  I wanted to make something different, something definitely chocolate—this is what I came up with"'
    ],
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c1',
      'c6',
    ],
    title: 'Lechon Fillipino-Style',
    author: 'Tata',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.nomnomboris.com/wp-content/uploads/2014/04/Lechon-@-Abe-1.jpg',
    duration: 90,
    descriptions: [
      'A verse from Tata: "The lechon pictured above was from my mother-in-laws’ 90th Birthday.'
          'It was a 70lb pig (dressed); I had the “help” of my brother-in-laws Ronnie Jones and Basilio Castro.  They watched over the beer." cont.. "My oldest memory of a lechon is back in the mid-1950s when I was about 7 years old and living in a Bracero camp in Summerton, AZ. My Dad was one of many Pinoys at the camp; he was a camp cook.  Having that many Pinoys in one place you can bet they would roast a lechon over an open fire frequently. Over the years while growing there were many times friends or family would get together to “kill a pig”  the majority of the time, the pig was butchered and cooked.  Fondly remember Dinuguan, saciado Another memory of a Lechon was from 1982, when my family visited the Philippines, (Davao, Minanao).  My uncle has just passed away, so I took the pig from his backyard to the market downtown where he was butcher and cooked.  Wow, what a sight!  Looks like there were 10 pigs cooking at one time. But my first time cooking a whole pig was while stationed in Izmir, Turkey in the mid 1980s.  Along with a couple of friends (Cuban & Puerto Rican) we cooked two pigs for a Squadron picnic. We loaded everything in our trusted yellow Toyota Van and head to the picnic grounds in the mountains the night before.  This were I got my first lesson in heat control.  It got windy during the night and we lost a lot of heat adding two hours to the cooking time. We had hungry military members waiting!! My next whole pig was while stationed in Cheyenne, WY.  Twice I purchased a pig from a local farmer and took him to a game processing plant to be butchered.   Both times it was for a fund raiser during Hispanic Heritage Month—I cooked them in the commissary parking lot.,  Man did I draw a lot of people, I sold out both times, the second time even before the lechon had finish cooking. During Christmas 2016, all the kids (Eva, Andy, Dee, & Liz) came to Arizona to visit.  I wanted to create a memory so I purchased a 40-lb pig for my son Andy and son-in-law Vinnie to cook.  Their first time cooking a whole pig; I’m sure they’ll never forget the process.  Don’t know why but they both said they would never try it again—wonder why?  Guess it’s the same reason, I didn’t get any photos. Then on Memorial Day 2017, My brother Mario and I cooked the lechon seen below at Compa’s  Bass place in Holtville"'
    ],
    ingredients: [
      '** Before you start **',
      'Make sure the pig is clean inside and out.  Shave/remove all hair on the skin and remove innards and then rise the pig and make sure there is no blood left on the inside. Truss  pig so there is NO Movement  Up&Down  or side-to-side.  A lesson my son Andy and son-in-law Vinnie learn the hard way.',
      'Crispy skin—This one of the things that make a pig on the spit a Filipino Lechon.  The key is to have the skin as dry as possible.  After adding the glaze (optional—see below), completely dry the pig with paper towels.  Then rub a very, very generous amount of salt on the whole pig.  Let the pig sit as the salt draws out the moisture from the pig.  As the salt get wet, remove, wipe dry, and add more salt – repeat.  Complete dry the pig (can even use a fan to help dry out the pig). '
          'As the pig is drying out – you can start your fire.',
      '**Lets Start',
      '1 whole dressed pig - should be about 1lb ~ 1 1/2lb per person. Depends what else is being served with the lechon. The 70-lb pig served over 100 people. But the pork was only one of the main dishes being served',
      '**Inside rub**',
      'Salt, black pepper, MSG, garlic granules, 5-spice or other Asian seasoning.',
      'Garlic, crushed',
      'Soy Sauce',
      '',
      '** Stuffing **',
      '1 ½ cup - Salt, pepper, MSG, 5-spice (optional), and adobo mix (optional)',
      '10-15 bundles - Lemon Grass ',
      '10-15 bundles - Green Onions',
      '½ cup - Star Anise',
      '6-10 bay leaves - broken down to small pieces',
      '1 or 2 - Banana leaves',
      '2 or 3 lbs bananas - (paraboiled) These are the Filipino saba banana.  A small banana normally used for cooking.  Sometimes called “burro” bananas',
      '5 cups garlic I used the pre-peeled garlic – crushed',
      '¼ cup - soy sauce.',
      '1 bottle - small (8 – 12 oz) water',
      '',
      '** Glaze **',
      '1 cup oil',
      '1 liter Sprite or 7up',
      'Soy sauce',
      'Carnation milk – optional',
      'NOTE: Glaze added only to give nice color and to help to crisp the skin. Apply glaze and let sit for few minutes.  HOWEVER, IT IS IMPORTANT TO HAVE THE PIG SKIN AS “DRY” AS POSSIBLE WHEN STARTING THE COOKING PROCESS.',
    ],
    steps: [
      'Cook over low heat about 220~250  should be able to hold hand at pig level for about  7~8 seconds. ',
      'Heat should be over the ham and the shoulders with very little heat (about 10 seconds) over the rib/stomach section.  The coals should not be directly under the pig but should be several inches to the side. ',
      'The skin of the lechon should be complete dry before starting the cooking process—improves the crispness of the skin.  If possible let lechon air dry for about an hour before starting the cooking process.  (this is the 3rd time I mentioned starting with “dry” pig – that important)',
      'Be prepared for the “dripping” as the lechon cooks.  Do not let dripping fall on coals otherwise you’ll get flare ups.',
      'Wipe the lechon once in a while to keep skin smooth, and even color.',
      'Use a needle to pop any bubbles that develop during the cooking. You should wipe the dripping from the skin of the lechon, to keep the skin even and smooth.',
      'A general guide:  it takes about an hour of cooking time for every 10 pounds of pig.  However, I plan on about 1 ½ hours per 10 pounds of pig.',
      'Pork should be cooked to an internal temperature of 145° (used to be 160° then US Dept of Agriculture dropped it to 145°)',
      'If using charcoal expect to use a pound of charcoal for every pound of lechon being cooked.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c1',
      'c6',
    ],
    title: 'Sweet and Sour Chicken',
    author: 'Tata',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.seasonsandsuppers.ca/wp-content/uploads/2016/09/sweet-sour6.jpg',
    duration: 20,
    descriptions: [
      'Tata\'s 50 year old recipe',
    ],
    ingredients: [
      '1 ea - Chicken breast cut into small bite-size pieces.  Can use pork or shrimp instead.',
      'Soy sauce',
      '2 - Cloves garlic minced',
      'Salt and pepper to taste',
      '** VEGGIES FOR SAUCE **',
      '1 ea - Bell pepper (green or red – or both) … cut into small squares',
      '1 ea - Medium onion … … cut into small squares',
      'Snow peas … about same amount as onions',
      '** SWEET AND SOUR SAUCE **',
      '1cup - Light brown sugar',
      '1 can - 20 oz Pineapple in syrup …  sliced or cubed; if sliced cut into cubes',
      '3 tbsp - Ketchup',
      '2 tbsp - Vinegar …. Normally use white distilled vinegar but can use rice vinegar or cider vinegar',
      '2 tbsp - Corn starch … mix with water to made a slurry',
      '5 drops - Red Food Coloring …. optional',
      '** BATTER FOR CHICKEN (OR PORK) **',
      '3 oz - All-purpose flour',
      '1 ½ oz - Corn starch',
      '1 tsp - baking soda',
      '1 ea - Egg',
      '2 tbsp - oil',
      '½ c - water (I like to use carbonated water – adds bubbles to the batter and make batter lighter)',
      '1 - pinch salt',
    ],
    steps: [
      'Stir fry bell pepper, onions, and snow peas in a little oil over medium high heat. Fry until bell peppers just start to blister … be careful not to overcook; remember veggies will continue to cook while in the sweet and sour sauce'
          'Remove from heat and set aside. ',
      'If you overcook the veggies will not be “crisp”.',
      'Mix all the batter ingredients together, mix well.',
      'Place chicken in batter then deep fry a few pieces of chicken at a time until golden brown.  Cook in batches and set aside.',
      'In a wok (or frying pan) add half of the pineapples chunks in a little oil, cook for a few minutes.',
      'Add brown sugar, about half of the pineapple juice, and ketchup.  Heat over medium until simmering… add vinegar and stir.',
      ' Slowly add corn starch slurry until mixture starts to thicken---remember mixture will continue to thicken',
      'Add veggies and chicken to mixture – stir to coat the veggies and chicken in sweet and sour sauce.',
      'Serve with rice.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
];
